services:
  zookeeper-1:
    image: bitnami/zookeeper:3.9.1
    ports:
      - "${ZOOKEEPER_1_PORT}:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-1:
    image: bitnami/kafka:3.5.2
    ports:
      - "${KAFKA_1_PORT}:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=${KAFKA_1_ADVERTISED_HOST_NAME}
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1:2181
    depends_on:
      - zookeeper-1

  kafka-ui-1:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "${KAFKA_UI_1_PORT}:8080"
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    depends_on:
      - kafka-1

  mongo-1:
    image: mongo:4.4.26
    ports:
      - "${MONGO_1_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_1_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_1_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_1_DATABASE}

  elasticsearch-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  
  kibana-1:
    image: docker.elastic.co/kibana/kibana:8.11.3
    depends_on:
      - elasticsearch-1
